### ISSUE TITLE
Not working on PowerToys 0.78.0

### ISSUE THREAD

**Issue by MaverickMartyn** [CoreyHayward/PowerToys-Run-ClipboardManager#1]
What the title says.
I'm not getting any errors or anything as far as I can tell. There's just no results upon entering "c: ".
I even checked the direct activation command in the PowerToys settings, to confirm that I entered it correctly.
Running PowerToys 0.78.0 and ClipboardManager 0.1.0.

Thanks for your work!

**Comment by CoreyHayward** [comment]
Hi, thanks for the report!

I don't seem to experience the issue you are reporting as it works fine on 0.78.0 for me:
<img width="371" alt="image" src="https://github.com/CoreyHayward/PowerToys-Run-ClipboardManager/assets/72159232/46c53547-21c9-4297-8336-980b1955089d">

If you try clearing your clipboard and then attempt to use the plugin again does it work?
I think there may be an issue with images in the clipboard history that causes the plugin to stop working which I will look into but would be great if you could confirm the behaviour.

**Comment by CoreyHayward** [comment]
I have published a release which fixes the image issue so this may be worth trying: https://github.com/CoreyHayward/PowerToys-Run-ClipboardManager/releases/tag/v0.2.0

**Comment by alihaiderismail** [comment]
I had a similar issue. I realized I had not enabled clipboard history in Windows settings. Enabling that got this plugin to work. You may want to mention that in the readme in the Installation section. 

Thanks for the great plugin!

**Comment by CoreyHayward** [comment]
@alihaiderismail Great point! I will add this to the readme, Thanks!

**Comment by CoreyHayward** [comment]
@MaverickMartyn Any updates on this?

**Comment by MaverickMartyn** [comment]
Sorry for the late reply.
Yes, it works perfectly! I don't know if the update did anything, but after updating and enabling Clipboard History it worked flawlessly. :)
Thank you!
I'll leave it up to you to close this, in case you want to track the readme.md update. I can't see that change atm.

**Comment by CoreyHayward** [comment]
Excellent, glad it's resolved. I added it to the pre-requisite section of the readme.
