### ISSUE TITLE
[Feature Request] Truncate multi-line clipboard results in search preview

### ISSUE THREAD

**Issue by SimonWalshIM** [CoreyHayward/PowerToys-Run-ClipboardManager#15]
When I copy something to the clipboard that has line breaks, the search results wind up taking up a majority of the screen. Ideally, this would show a one-line preview of the clipboard instead of showing multiple lines in PowerToys Run search results.

### How it looks now:

![Screenshot 2024-11-25 122747](https://github.com/user-attachments/assets/2d27899c-8ed9-4cb6-9154-121f2fc0546e)

### How I think it should look:

![Screenshot 2024-11-25 123419](https://github.com/user-attachments/assets/5bf7c89f-ad9f-402c-a285-e7932edc8fbc)

Thanks! I really appreciate your time.

**Comment by CoreyHayward** [comment]
Thanks a lot for the suggestion @SimonWalshIM!

This has been implemented and is available in the latest release -> https://github.com/CoreyHayward/PowerToys-Run-ClipboardManager/releases/tag/v0.9.0
