### ISSUE TITLE
[Bug] Unable to view clipboard contents

### ISSUE THREAD

**Issue by arunk** [CoreyHayward/PowerToys-Run-ClipboardManager#5]
Hi this seems like a really useful plugin, if I can get it to work. I have installed the plugin in the path mentioned, and I can see it in the list of Plugins in PowerToys Run, and it is enabled and it's shortcut is set to the default c:. When I click `Alt+Space`, I can see the clipboard manager listed in the list of plugins, and it shows its shortcut correctly 'c:'. But when I select it, or type c:, the list is empty. I have copied from Windows , notepad, VS Code, my WSL 2 distro, all of it. But it doesn't seem to matter. I can't see anything in the list of clipboard history. I found the other issue on this repo mentioned missing Clipboard entries and you had asked to check the logs. So here is what I found in the logs: (Just a few entries about ClipboardManager):
```
[2024-09-04 02:44:25.6073] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <ClipboardManager> is <99ms>

[2024-09-04 02:44:26.4585] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <ClipboardManager> is <99ms>

[2024-09-04 02:52:20.2244] [WARN] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::229]
PluginManager.QueryForPlugin ClipboardManager. Query cost - 79 milliseconds
```
There doesn't appear to be any errors in the log file. Just these few entries about ClipboardManager. I found PowerToys had updated after I installed it, I have updated to the latest version, but I'm unable get this ClipboardManager to work. 

Please let me know if you need any more information to trouble shoot this issue.

Thansk,

**Comment by CoreyHayward** [comment]
Hi @arunk 

Could you first check that you have clipboard history enabled in Windows. You can do this by pressing Windows key + v. 
It will give you the option to enable if it isn't already.

If this isn't the case then let me know and I can take a further look into other potential issues!

Thanks!

**Comment by arunk** [comment]
That was it! I was going to suggest updating the README, but I just checked and realized I missed seeing this under requirements. Sorry about that! This is great! I'll be able to copy and paste all kinds of things between all my editors. Thanks so much for this

**Comment by CoreyHayward** [comment]
I think a couple of people have had this issue too so I've added in some detection in the [latest release](https://github.com/CoreyHayward/PowerToys-Run-ClipboardManager/releases/tag/v0.4.0) to check if the windows clipboard history is not enabled and also provide the ability to enable it directly via the plugin. 

Hopefully this helps some people in the future!
