### ISSUE TITLE
Clear Clipboard

### ISSUE THREAD

**Issue by able16** [CoreyHayward/PowerToys-Run-ClipboardManager#6]
Possible to add `Clear Clipboard` to the list after activating with `c:`? 
Have it at the bottom of the stack and/or an option to invoke it with a PowerToys Run activation command like `cc:`.

**Comment by CoreyHayward** [comment]
Clipboard history is easily clearable via the Windows history (Windows key + C) then selecting clear all but I could potentially add a shortcut here too if you still think it would be useful, something like `c: -c/--clear` could work?

**Comment by able16** [comment]
Yeah a hands-on shortcut would help greatly. Unless text input is foreground and active, it'll pop-up on the bottom right of the screen. The pause in workflow for those who spend 75% of their time with two hands on keyboard is enough to wonder why there isn't a shortcut for it in the first place, or why it's not drawn by the cursor.

I think the solution you proposed is good. It looks like `c:-` is ambiguous that it'll invoke it with those few keystrokes.

**Comment by CoreyHayward** [comment]
Hey @able16,

I have implemented this and its available in the latest release [here](https://github.com/CoreyHayward/PowerToys-Run-ClipboardManager/releases/tag/v0.5.0)

Thanks for the suggestion!
